language: go

go:
- master
- 1.x
- 1.7.x
- 1.8.x
- 1.9.x
- 1.10.x
- 1.11.x

sudo: false

before_install:
- export GO111MODULE=on
- export GOFLAGS=-mod=vendor

script:
- make test

notifications:
  slack: octolab:1eMS7IqOArBipiu31jYVd0cN
